name: You-AI Full Pipeline

on:
  workflow_dispatch:        # Allows manual run
  schedule:
    - cron: '0 4 * * *'     # Auto-run daily at 4 AM UTC

jobs:
  scaffold-folders:
    name: Scaffold Folder Structure
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run PowerShell Script
        run: ./Initialize-YouAI.ps1
        shell: pwsh

  generate-script:
    name: Generate Script with OpenAI
    runs-on: windows-latest
    needs: scaffold-folders

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Video Script
        run: ./10_AutomationScripts/GenerateScript.ps1 -Topic "Top 5 AI Tools That Save You Time" -OutputFile "01_Scripts/video_001.txt"
        shell: pwsh
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  upload-video:
    name: Upload to YouTube
    runs-on: ubuntu-latest
    needs: generate-script

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install YouTube API Client
        run: npm install @googleapis/youtube

      - name: Upload Video
        run: |
          echo "${{ secrets.CLIENT_SECRET_JSON }}" > client_secret.json
          node 10_AutomationScripts/upload_to_youtube.js \
            "05_FinalVideos/video_001.mp4" \
            "Top 5 AI Tools That Save You Time" \
            "Here are 5 AI tools to boost your productivity." \
            "AI,tools,automation,time-saving"
        env:
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
