name: You-AI Folder Scaffold

on:
  workflow_dispatch:        # Allows manual triggering from GitHub UI
  schedule:
    - cron: '0 4 * * *'     # Runs daily at 4 AM UTC

jobs:
  scaffold-folders:
    name: Scaffold You-AI Directory Structure
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run PowerShell Script
        run: ./Initialize-YouAI.ps1
        shell: pwsh
