name: You-AI Folder Scaffold

on:
  workflow_dispatch:        # Manual trigger from GitHub UI
  schedule:
    - cron: '0 4 * * *'     # Daily auto-run at 4 AM UTC

jobs:
  scaffold-folders:
    name: Scaffold Folder Structure
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Run PowerShell Scaffolding Script
        run: ./Initialize-YouAI.ps1
        shell: pwsh
